version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'crate-ci/typos'
      - dependency-name: 'actions/dependency-review-action'
        versions:
          # https://github.com/actions/dependency-review-action/issues/759
          - '4.3.1'
          - '4.3.0'
          # https://github.com/actions/dependency-review-action/issues/493
          - '3.0.5'
      - dependency-name: 'cachix/install-nix-action'
        versions:
          - '31.5.0' # Don't use 31.5.0 for now, to avoid Nix 2.30.0. See https://github.com/actions/runner-images/issues/12574#issuecomment-3060801512
