# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      - go test ./pkgs/resume/...
  fmt:
    cmds:
      - gofumpt -w .
      - dprint fmt
      - git ls-files '*.nix' | xargs nix fmt
  lint:
    cmds:
      - go vet ./pkgs/...
      - gofumpt -d .
      - dprint check
      - typos . .github .vscode
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
      - git ls-files | xargs nix run github:kachick/selfup/v1.2.0 -- list -check
  selfup:
    cmds:
      - git ls-files | xargs nix run github:kachick/selfup/v1.2.0 -- run
