# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: fmt
      - task: lint
      - task: test
  start:
    cmds:
      - ./review.bash {{.CLI_ARGS}}
  resume:
    env:
      GH_FORCE_TTY: '50%'
    cmds:
      - gh run list --workflow 'nixpkgs-review.yml' | fzf --ansi --header-lines=1 --nth 6 --bind 'enter:become(./resume.bash {6})'
  check:
    deps:
      - task: test
      - task: lint
  test:
    cmds:
      - echo 'Update here'
  fmt:
    cmds:
      - dprint fmt
      - git ls-files '*.nix' | xargs nix fmt
  lint:
    cmds:
      - dprint check
      - typos . .github .vscode
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
      - git ls-files | xargs selfup list -check
  selfup:
    cmds:
      - git ls-files | xargs selfup run
  deps:
    cmds:
      - nix --version
      - nil --version
      - task --version
      - dprint --version
      - typos --version
      - selfup -version
