name: 🧪
# https://stackoverflow.com/questions/71155641/github-actions-how-to-view-inputs-for-workflow-dispatch
run-name: '${{ inputs.pname }}: ${{ inputs.repository }}#${{ inputs.ref }}'
# run-name: '[Experimental] plemoljp-nf: kachick/nixpkgs#aa32ada9e1344d0a3abb64ffc806f8b07732fe4c' # Enable only when developing
on:
  # pull_request: # Enable only when developing
  workflow_dispatch:
    inputs:
      pname:
        description: 'Package name'
        required: true
        type: string
      repository:
        description: 'GitHub repository'
        # Cannot use ${{ github.repository_owner }} here.
        default: 'kachick/nixpkgs'
        required: true
        type: string
      ref:
        description: 'git ref'
        default: 'nixpkgs-unstable'
        required: true
        type: string
      runners:
        description: 'Runners'
        required: true
        # It does not alloow list and multiline string.
        #   - https://github.com/orgs/community/discussions/12882
        #   - https://github.com/actions/toolkit/issues/184
        type: string
        # - ubuntu-24.04 # x86_64
        # - ubuntu-24.04-arm # aarch64-Linux
        # - macos-15 # aarch64
        # - macos-13 # x86_64
        default: |
          [ "ubuntu-24.04", "ubuntu-24.04-arm", "macos-15", "macos-13" ]

# env: # Enable only when developing
#   pname: 'plemoljp-nf'
#   repository: 'kachick/nixpkgs'
#   ref: 'aa32ada9e1344d0a3abb64ffc806f8b07732fe4c'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: '${{ fromJson(inputs.runners) }}'
    runs-on: ${{ matrix.runner }}
    # timeout-minutes: 180 # Any limitations might not fit for this repository. So temporary disabling
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: '${{ inputs.repository }}'
          ref: '${{ inputs.ref }}'

      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16

      - name: Outputs nix version and the config
        run: |
          nix --version
          nix config show

      - name: Build
        run: |
          nix-build --attr 'pkgs.${{ inputs.pname }}'

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          # Should trim `-` for path available if using inputs.repository
          name: 'build-${{ inputs.pname }}-${{ inputs.ref }}-${{ runner.arch }}-${{ runner.os }}'
          path: './result*'
          if-no-files-found: 'error'
          # This is a broken change in their minor version updates. See https://github.com/actions/upload-artifact/commit/cb6558bb10fe4afe4054d0be4b3136e673eb5e7f and https://github.com/actions/upload-artifact/pull/598
          include-hidden-files: 'true' # Required for `bin/.bin-wrapped`
