name: 🐚
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/devshell.yml'
      - '**.nix'
      - 'flake.*'
      - '.envrc'
      - 'Taskfile.yml'
  pull_request:
    paths:
      - '.github/workflows/devshell.yml'
      - '**.nix'
      - 'flake.*'
      - '.envrc'
      - 'Taskfile.yml'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  tasks:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          # - ubuntu-24.04-arm # aarch64-linux
          # - macos-26 # aarch64
          # - macos-15-intel # x86_64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: NixOS/nix-installer-action@main # There are no tagged releases
        with:
          extra-conf: |
            sandbox = true
            accept-flake-config = true
      - name: Ensure sandbox mode
        run: |
          set -x
          [[ "$(nix config show sandbox)" == 'true' ]]
      - run: nix flake check
      - run: nix flake show
      - name: Install direnv
        run: |
          rev="$(nix eval --raw --impure --expr '(builtins.fromJSON (builtins.readFile ./flake.lock)).nodes.nixpkgs.locked.rev')"
          nix profile add "github:NixOS/nixpkgs/${rev}#direnv"
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - run: task check
