name: Go
on:
  push:
    branches: [main]
    paths:
      - 'pkgs/**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'go.work'
      - '.github/workflows/go.yml'
  pull_request:
    branches: [main]
    paths:
      - 'pkgs/**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'go.work'
      - '.github/workflows/go.yml'

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.work'
          cache: true

      - name: Vet
        run: go vet ./pkgs/resume/...

  test:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.work'
          cache: true

      - name: Test
        run: go test -v ./pkgs/resume/...
