name: 🛠️👀
# https://stackoverflow.com/questions/71155641/github-actions-how-to-view-inputs-for-workflow-dispatch
# https://docs.github.com/ja/actions/reference/evaluate-expressions-in-workflows-and-actions#format
run-name: |
  ${{ inputs.pr-number && format('NixOS/nixpkgs#{0}', inputs.pr-number) || format('nixpkgs-review: {0}', inputs.args) }}
# run-name: '[Experimental]' # Enable only when developing
on:
  # pull_request: # Enable only when developing
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'PR number'
        required: false
        type: string # Don't use `number` type here, GitHub Apps in both Android and iOS forces them as 'Float'
        default: ''
      runners:
        description: 'Runners'
        required: true
        # It does not allow list and multiline string.
        #   - https://github.com/orgs/community/discussions/12882
        #   - https://github.com/actions/toolkit/issues/184
        type: string
        # - ubuntu-24.04 # x86_64
        # - ubuntu-24.04-arm # aarch64-Linux
        # - macos-15 # aarch64
        # - macos-13 # x86_64
        default: |
          [ "ubuntu-24.04", "ubuntu-24.04-arm", "macos-15", "macos-13" ]
      args:
        # Use this option if your requirement is not simple. Might be needed for mass-rebuilds.

        # For example:
        # ```
        # pr 380842 -p crystalline -p ameba -p ameba-ls -p mint --package-regex 'crystal_.*' --print-result
        # ```

        # See https://github.com/Mic92/nixpkgs-review/blob/d46f823c058c445e8b50ca93b32c495b3dda1b25/README.md?plain=1#L312-L347 for detail
        description: 'Customized arguments. Ignore `pr-number`'
        required: false
        type: string
        default: ''

# env:
#   pr-number: '42' # Enable only when developing

jobs:
  review:
    strategy:
      fail-fast: false
      matrix:
        runner: '${{ fromJson(inputs.runners) }}'
    continue-on-error: true # Simply avoiding the state for #91
    runs-on: ${{ matrix.runner }}
    # timeout-minutes: 180 # Any limitations might not fit for this repository. So temporary disabling
    steps:
      - name: Make sure dependent environments
        id: get-meta
        run: | # shell
          #
          # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/nixpkgs_review/builddir.py#L24-L36
          echo "cache_dir=${XDG_CACHE_HOME:-${HOME}/.cache}" | tee -a "$GITHUB_OUTPUT"

      - name: Validate options
        if: ${{ inputs.args != '' && inputs.pr-number != '' }}
        run: 'exit 2'

      - name: Validate PR number
        if: ${{ inputs.pr-number != '' }}
        run: |
          input="${{ github.event.inputs.pr-number }}"

          # Check if the input is a positive integer (greater than 0)
          if ! [[ "$input" =~ ^[1-9][0-9]*$ ]]; then
            echo "❌ Error: The input \"$input\" is not a valid positive integer (e.g., 1, 42)."
            exit 1
          fi

          echo "✅ Input \"$input\" is a valid positive integer."

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: 'NixOS/nixpkgs'

      - name: Make sure the shallow clone or not
        # Often needed for debugging purpose. See GH-26 https://github.com/Mic92/nixpkgs-review/pull/426/files#diff-068fea7dedadb885b7dcccc0fe1bc843caa6f1da0c6622ee7a7d56e99c31475aR598-R606
        run: git rev-parse --is-shallow-repository

      - uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31.4.1 - Don't use DeterminateSystems/nix-installer-action that cannot specify the Nix version
        with:
          # Syntax example: https://github.com/DeterminateSystems/nix-installer-action/blob/c723f3a885e3f1d866d91f4f0c33dd44b1fc7c60/.github/workflows/ci.yml#L128-L129
          extra_nix_config: |
            sandbox = true
      - name: Outputs nix version and the config
        run: |
          nix --version
          nix config show

      - name: Ensure sandbox mode
        run: |
          set -x
          [[ "$(nix config show sandbox)" == 'true' ]]

      - name: Run binary-cached nixpkgs-review for PR
        if: ${{ inputs.pr-number != '' }}
        env:
          # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/README.md?plain=1#L239-L260
          GITHUB_TOKEN: '${{ github.token }}'
        run: | # shell
          #
          nix run 'github:NixOS/nixpkgs/nixpkgs-unstable#nixpkgs-review' -- pr '${{ inputs.pr-number }}' --print-result

      - name: Run binary-cached nixpkgs-review for custom args
        if: ${{ inputs.args != '' }}
        env:
          # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/README.md?plain=1#L239-L260
          GITHUB_TOKEN: '${{ github.token }}'
        run: | # shell
          #
          nix run 'github:NixOS/nixpkgs/nixpkgs-unstable#nixpkgs-review' -- ${{ inputs.args }}

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: 'nixpkgs-review-files-pr-${{ inputs.pr-number }}-${{ runner.arch }}-${{ runner.os }}'
          path: '${{ steps.get-meta.outputs.cache_dir }}/nixpkgs-review/'
          if-no-files-found: 'error'
          # This is a broken change in their minor version updates. See https://github.com/actions/upload-artifact/commit/cb6558bb10fe4afe4054d0be4b3136e673eb5e7f and https://github.com/actions/upload-artifact/pull/598
          include-hidden-files: 'true' # Required for `bin/.bin-wrapped`

  report:
    needs: [review]
    uses: ./.github/workflows/report.yml
    with:
      run_id: '${{ github.run_id }}'
