name: 👁️
on:
  pull_request:
  # TODO: workflow_dispatch:

jobs:
  review:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04 # x86_64
          # Add ARM based Linux runner if available in free plan
          # https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/
          - macos-15 # aarch64
    # - TODO: macos-13 # x86_64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 180
    steps:
      - name: Make sure dependent environments
        id: get-meta
        run: | # shell
          #
          # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/nixpkgs_review/builddir.py#L24-L36
          echo "cache_dir=${XDG_CACHE_HOME:-${HOME}/.cache}" | tee -a "$GITHUB_OUTPUT"
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: 'NixOS/nixpkgs'
      - uses: DeterminateSystems/nix-installer-action@b92f66560d6f97d6576405a7bae901ab57e72b6a # v15
      # Don't add DeterminateSystems/magic-nix-cache-action in this workflow. Caching is not reasonable for this use

      # TODO: Prefer nixpkgs version of nixpkgs-review since updated to https://github.com/Mic92/nixpkgs-review/commit/055465e55d131ffb1e1617f46d3bade0b87bbe69 or higher
      - run: | # shell
          #
          nix run 'github:Mic92/nixpkgs-review' -- pr 'https://github.com/NixOS/nixpkgs/pull/353993' --print-result

      - name: Upload artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: 'nixpkgs-review-files-${{ github.sha }}-${{ matrix.runner }}'
          path: '${{ steps.get-meta.outputs.cache_dir }}/nixpkgs-review/'
          if-no-files-found: 'error'
