name: 👁️
# https://stackoverflow.com/questions/71155641/github-actions-how-to-view-inputs-for-workflow-dispatch
# run-name: 'NixOS/nixpkgs#${{ inputs.pr-number }}'
run-name: '[Experimental]' # Enable only when developing
on:
  pull_request: # Enable only when developing
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'Target PR number'
        required: true
        type: number
      runners:
        description: 'Target runners'
        required: true
        # It does not alloow list and multiline string.
        #   - https://github.com/orgs/community/discussions/12882
        #   - https://github.com/actions/toolkit/issues/184
        type: string
        # - ubuntu-24.04 # x86_64
        # - ubuntu-24.04-arm # aarch64-Linux # It raising errors. See GH-43
        # - macos-15 # aarch64
        # - macos-13 # x86_64
        default: |
          [ "ubuntu-24.04", "macos-15", "macos-13" ]

# env:
#   pr-number: '42' # Enable only when developing

jobs:
  review:
    strategy:
      fail-fast: false
      matrix:
        runner: ${{ fromJson('[ "ubuntu-24.04", "macos-15", "macos-13" ]') }}
    runs-on: ${{ matrix.runner }}
    # timeout-minutes: 180 # Any limitations might not fit for this repository. So temporary disabling
    steps:
      - name: Make sure dependent environments
        id: get-meta
        run: | # shell
          #
          # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/nixpkgs_review/builddir.py#L24-L36
          echo "cache_dir=${XDG_CACHE_HOME:-${HOME}/.cache}" | tee -a "$GITHUB_OUTPUT"

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: 'NixOS/nixpkgs'

      - name: Make sure the shallow clone or not
        # Often needed for debugging purpose. See GH-26 https://github.com/Mic92/nixpkgs-review/pull/426/files#diff-068fea7dedadb885b7dcccc0fe1bc843caa6f1da0c6622ee7a7d56e99c31475aR598-R606
        run: git rev-parse --is-shallow-repository

      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16

      - name: Outputs nix version and the config
        run: |
          nix --version
          nix config show

      - name: Run binary-cached nixpkgs-review
        env:
          # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/README.md?plain=1#L239-L260
          GITHUB_TOKEN: '${{ github.token }}'
        run: | # shell
          #
          nix run 'github:NixOS/nixpkgs/nixpkgs-unstable#nixpkgs-review' -- pr '${{ inputs.pr-number }}' --print-result

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: 'nixpkgs-review-files-pr-${{ inputs.pr-number }}-${{ runner.arch }}-${{ runner.os }}'
          path: '${{ steps.get-meta.outputs.cache_dir }}/nixpkgs-review/'
          if-no-files-found: 'error'

  report:
    needs: [review]
    uses: ./.github/workflows/report.yml
    with:
      run_id: '${{ github.run_id }}'
