name: 👁️
on:
  # pull_request: # Enable only when developing
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'Target PR number'
        required: true
        type: number

jobs:
  review:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04 # x86_64
          - ubuntu-24.04-arm # aarch64-Linux
          - macos-15 # aarch64
          - macos-13 # x86_64
    runs-on: ${{ matrix.runner }}
    # timeout-minutes: 180 # Any limitations might not fit for this repository. So temporary disabling
    steps:
      - name: Make sure dependent environments
        id: get-meta
        run: | # shell
          #
          # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/nixpkgs_review/builddir.py#L24-L36
          echo "cache_dir=${XDG_CACHE_HOME:-${HOME}/.cache}" | tee -a "$GITHUB_OUTPUT"

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: 'NixOS/nixpkgs'

      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      # Don't add DeterminateSystems/magic-nix-cache-action in this workflow. Caching is not reasonable for this use

      - name: Outputs nix version and the config
        run: |
          nix --version
          nix config show

      # TODO: Prefer nixpkgs version of nixpkgs-review since updated to https://github.com/Mic92/nixpkgs-review/commit/055465e55d131ffb1e1617f46d3bade0b87bbe69 or higher
      - name: Run latest nixpkgs-review
        env:
          # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/README.md?plain=1#L239-L260
          GITHUB_TOKEN: '${{ github.token }}'
        run: | # shell
          #
          nix run 'github:NixOS/nixpkgs/nixpkgs-unstable#nixpkgs-review' -- pr '${{ inputs.pr-number }}' --print-result --eval local

      - name: Upload artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: 'nixpkgs-review-files-pr-${{ inputs.pr-number }}-${{ runner.arch }}-${{ runner.os }}'
          path: '${{ steps.get-meta.outputs.cache_dir }}/nixpkgs-review/'
          if-no-files-found: 'error'
