name: 👁️
on:
  pull_request:
  # TODO: workflow_dispatch:

jobs:
  tasks:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04 # x86_64
          # Add ARM based Linux runner if available in free plan
          # https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/
          - macos-15 # aarch64
    # - TODO: macos-13 # x86_64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: 'NixOS/nixpkgs'
      - uses: DeterminateSystems/nix-installer-action@b92f66560d6f97d6576405a7bae901ab57e72b6a # v15
      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
      - run: |
          nix-shell --arg nixpkgs './.' --command 'nixpkgs-review pr "https://github.com/NixOS/nixpkgs/pull/354280" --print-result'
